server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ronit
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  app:
    cors:
      allowed-origins: http://localhost:3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ronitrangwani25@gmail.com
    password: ymne qjdu uskm ewst
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true